Take two arguments, --default-wm and --sm-client-id and run a
Mon Jan 10 17:26:50 2000  George Lebl <jirka@5z.com>

	* gnome-wm: Take two arguments, --default-wm and --sm-client-id
	  and run a windowmanager with the client id translated into an
	  appropriate option for any given windowmanager.

	* default.in: add the --sm-client-id option and always call gnome-wm
	  script and pass the @WINDOW_MANAGER@ configure variable as the
	  --default-wm

	* gnome-wm.1: update for the two options and the new behaviour and
	  fix a couple spelling errors

diff --git a/gnome-session/gnome-wm b/gnome-session/gnome-wm
--- a/gnome-session/gnome-wm
+++ b/gnome-session/gnome-wm
@@ -7,14 +7,50 @@
 # the first one that is found in the users's PATH
 #
 
+# sm-client-id value
+SMID=
+# default-wm value
+DEFWM=
+
+#read in the arguments
+GET=
+for n in "$@" ; do
+  case "$GET" in
+    smid)
+      SMID=$n
+      GET=
+      ;;
+    defwm)
+      DEFWM=$n
+      GET=
+      ;;
+    *)
+      case "$n" in
+        --sm-client-id)
+          GET=smid
+          ;;
+        --default-wm)
+          GET=defwm
+          ;;
+      esac
+      ;;
+  esac
+done
+
+# WINDOW_MANAGER overrides all
+
 if [ -z "$WINDOW_MANAGER" ] ; then
-  for wm in sawmill enlightenment icewm wmaker fvwm2 fvwm twm ; do
-    check=`which $wm`
-    if [ $? -eq 0 ] ; then
-      WINDOW_MANAGER=$check
-      break
-    fi
-  done
+  if [ -z "$DEFWM" -o "x$DEFWM" = "xgnome-wm" ]; then
+    for wm in sawmill enlightenment icewm wmaker fvwm2 fvwm twm kwm ; do
+      check=`which $wm`
+      if [ $? -eq 0 ] ; then
+        WINDOW_MANAGER=$check
+        break
+      fi
+    done
+  else
+    WINDOW_MANAGER=$DEFWM
+  fi
 fi
 
 # If no window manager can be found, we default to xterm
@@ -22,6 +58,22 @@ fi
 if [ -z "$WINDOW_MANAGER" ] ; then
   echo "WARNING: No window manger can be found."
   WINDOW_MANAGER=xterm
+fi
+
+# Now create options OPT1 and OPT2 based on the windowmanager used
+OPT1=
+OPT2=
+if [ ! -z "$SMID" ] ; then
+  case `basename $WINDOW_MANAGER` in
+    sawmill)
+      OPT1=--sm-client-id=$SMID
+      ;;
+    enlightenment|twm)
+      OPT1=-clientId
+      OPT2=$SMID
+      ;;
+    #FIXME: add all other windowmanagers here with their proper options
+  esac
 fi
 
 # Store the selected WM so the wm-properties-capplet can find it
@@ -37,5 +89,6 @@ cat > $HOME/.gnome/default.wm <<EOF
 WM=$WINDOW_MANAGER
 EOF
 
-exec $WINDOW_MANAGER $*
+exec $WINDOW_MANAGER $OPT1 $OPT2
 
+echo "ERROR: No window manager could run!"
